### ISSUE TITLE
Remove all "microservices-infrastructure" references

### ISSUE THREAD

**Issue by siddharthist** [CiscoCloud/mantl#1124]
The README still mentions that this project was formerly known as "microservices-infrastructure", we should complete the transition by the next major release.
```
$ grep -ri "microservices-infrastructure" | wc -l 
70
```

**Comment by sehqlr** [comment]
I started working on this, and I'll post a PR soonish. There are a few questions that I have:
1. Should we delete the FAQ about the rename?
2. Quite a few references are in terraform.py. Considering #1120, I'd suggest that we open an issue in that repo; then those changes would move downstream to here
3. A couple of the mentions are Vagrant box related. That should be fixed in PRs when the new boxes are made

**Comment by siddharthist** [comment]
Closed in #1134
