### ISSUE TITLE
need clearer explanation of traefik/route53 in docs for kong example

### ISSUE THREAD

**Issue by darKoram** [CiscoCloud/mantl#1305]
in sample.yml/matl.yml i set
traefik_marathon_domain: "*.marathon.k4b4-mantl.<mydomain>"
domain: "c1.io"
subdomain: ".k4b4-mantl"

In route53 I see
*.k4b4-mantl .<mydomain>  ALIAS k4b4-mantl-traefik-elb-693411772.us-west-2.elb.amazonaws.com

In traefik UI I see
frontend                                                                                 
route-host-kong	Host	kong.*.marathon.k4b4-mantl.<mydomain>
backend
server-kong-<uuid>	http://<domain>-worker-003.node.consul:<kong_api_port>

The kong.*.marathon.<mydomain> seems strange.  Is it right?  Would have expected kong.marathon.<mydomain>

I would expect to be able to be routed to my kong servers (eg. mockbin) via something like
kong.mockbin.marathon.<mydomain> 
kong.marathon.<mydomain>/mockbin
mockbin.kong.marathon.<mydomain>

Kong examples doesn't update iptables so you can't access the port except for on localhost.

Question: Can you have two traefik providers at the same time?  Eg. marathon and docker.

- Ansible version (`ansible --version`): 
- Python version (`python --version`):
- Git commit hash or branch: 
- Cloud Environment: 
- Terraform version (`terraform version`):

**Comment by siddharthist** [comment]
@darKoram I don't have a domain name to test with, so I can't really help you with the route53 configuration. Based on your configuration, I would expect Kong to be available at kong.marathon.k4b4-mantl.c1.io. Where do you get `mockbin` from?

You should look at the [Traefik documentation](https://docs.traefik.io/) for more information about its configuration.

**Comment by kbroughton** [comment]
I think i added mockbin following the kong tutorial from mashape.
https://getkong.org/docs/0.4.x/tutorials/hello-world/

This issue is pretty old and you may close.  I'll make a PR if i get back to kong stuff.

Answering my final question:
Question: Can you have two traefik providers at the same time? Eg. marathon and docker.
Yes: as per the traefik docs you can have multiple backends.

I believe my main issue was that 
traefik_marathon_domain: "*.marathon.k4b4-mantl."
should be
traefik_marathon_domain: ".k4b4-mantl"
or 
traefik_marathon_domain: ".k4b4-mantl.service.consul"
depending on what marathon displays in the UI as the address of a task when you click on it.
They must match for traefik/kong to work.

**Comment by siddharthist** [comment]
@kbroughton Sorry we weren't able to be of more help on this. :rat: I'm glad you figured it out!
