### ISSUE TITLE
Accessing ELK stack from external client

### ISSUE THREAD

**Issue by dutronlabs** [CiscoCloud/mantl#1318]
I'm working on trying to send data from my platform to the ELK stack running on Mantl (as part of Apprenda integration efforts), however it does not appear that an ES/Logstash pipe is exposed for transmission.

If this is true, can we configure an endpoint that external clients can send data/logs? 

Also, can we have a list of externally exposed resources stored somewhere (ie. consul?)

**Comment by stevendborrelli** [comment]
@ryane can you look at this?

**Comment by ryane** [comment]
Can you describe your scenario a little more? We'd love to develop and/or document a good solution but below are some quick thoughts.

We don't expose the elasticsearch nodes outside the cluster by default. I believe you would just have to open the necessary ports (what platform are you on?) to your external clients. In the updated ELK addon (see #1312), this will be a little easier since we stand up an Elasticsearch client node that listens on the known standard ports (9200 http, 9300 transport). But, unless your external clients are configured to resolve Mantl Consul DNS, you'd have do some kind of service discovery to to make sure you are routing to the correct node(s) from your external clients.

You can also create a new client node just for this purpose using the elasticsearch-client package. Here is an example:

`client.json`:

```json
{
  "name": "elasticsearch-client",
  "id": "es-external",
  "config": {
    "elasticsearch-client": {
      "id": "es-external",
      "cluster-name": "mantl",
      "elasticsearch-service": "transport_port.elasticsearch-executor-mantl",
      "client-port": 9200,
      "transport-port": 9300
    }
  }
}
```

Install it:

```shell
curl -sku admin:password -d @client.json https://your-control-node/api/1/packages
```

You'd still have to discover the node it is running on for your external client as described above.

**Comment by dutronlabs** [comment]
I'm running this in GCE. 

I'll give that a go, thanks! Keep you posted.

**Comment by siddharthist** [comment]
@dutronlabs Did @ryane's solution work out for you?

**Comment by ryane** [comment]
going to close this for now. @dutronlabs please open a new issue if you have any more issues with this. thanks!
