### ISSUE TITLE
Handlers aren't defined when running addons

### ISSUE THREAD

**Issue by siddharthist** [CiscoCloud/mantl#1343]
The `reload consul` handler is defined in `roles/handlers`, but might be undefined when running an addon. 
```
TASK: [distributive | de-register deprecated distributive tests with consul] ***
changed: [resching-aws-control-02] => (item=chronos)
changed: [resching-aws-control-01] => (item=chronos)
changed: [resching-aws-control-03] => (item=chronos)
ok: [resching-aws-control-02] => (item=chronos)
ok: [resching-aws-control-03] => (item=chronos)
ok: [resching-aws-control-01] => (item=chronos)
ERROR: change handler (reload consul) is not defined
```
Two ideas:
 1. Add `handlers` role as a dependency to those that use it
 2. Add `reload consul` as a handler explicitly to each role that uses it. 

Either of these should be applied to every role that uses anything from `roles/handlers`. 

- Git commit hash or branch:  7b076b9
- Cloud Environment: any

**Comment by ryane** [comment]
would another option be to add the handler to the distributive role? that's the dependency that is triggering that handler as far as I could tell

**Comment by siddharthist** [comment]
@ryane I think that's what I mean by (2), unless I'm misunderstanding you.

**Comment by kbroughton** [comment]
This problem might be resolved by the following PR if mantl moves to ansible 2.0
https://github.com/ansible/proposals/pull/4

**Comment by ryane** [comment]
@siddharthist I think we're on the same page. in the case of logstash and chronos, at least, the `reload consul` handler is only notified because of the dependency on the distributive role. So, I was just thinking that we would only need to add the handler to the distributive role itself rather than the logstash or chronos roles (even though I did the opposite in https://github.com/CiscoCloud/mantl/pull/1342/files#diff-3edf8ebe9114681cdb3b6d272a142380R33 before I fully understood what the problem was)
