### ISSUE TITLE
TLS certificates should be valid for *.service and *.node

### ISSUE THREAD

**Issue by siddharthist** [CiscoCloud/mantl#1435]
When working on #1406, I used the short DNS form for a service, i.e. without the `consul_dns_domain`, and got the following message:
```
May 10 07:33:01 lb0-control-01 docker[21812]: time="2016-05-10T07:33:01Z" level=error msg="Put https://consul.service:8500/v1/session/create: x509: certificate is valid for localhost, *.node.consul, *.service.consul, not consul.service"
```
The cert we deploy should also be valid for those short constructions. 

- Ansible version (`ansible --version`): 1.9.4
- Python version (`python --version`): n/a
- Git commit hash or branch: master
- Cloud Environment: aws
- Terraform version (`terraform version`): 0.6.14

**Comment by kbroughton** [comment]
I had end-to-end ssl over traefik working from a month-old mantl, but it seems that the latest pull of mantl master no longer has marathon registering names as mantl-worker-001.node.consul. Rather they show up as just mantl-worker-001 in the marathon UI. I can ping mantl-worker-001, but wIthout a domain, there is no way I can get a self signed CA wildcard cert for traefik to communicate via ssl to the backend. What controls the marathon domain_dns reported for workers?

level=error msg="Error forwarding to https://k9b9-mantl-worker-001:31619, err: x509: certificate is valid for localhost, *.node.consul, *.service.consul, *.node.c1.io, *.c1.io,  not k9b9-mantl-worker-001

Have you considered using vault to issue the certs on demand, for both worker nodes and containers?  We have started on this, but still a WIP here
https://github.com/CognitiveScale-Solutions/docker-utils/blob/master/base_container_startup.sh

This script is burned into all our base containers and is called by whatever startup script/entrypoint runs the container.

**Comment by distributorofpain** [comment]
this is problematic for me as i am using the end to end setup... or atleast was trying.

**Comment by kbroughton** [comment]
My workaround for now is the following:

Traefik sends to backends that marathon now references as mantl-worker-001 to -003.  No wildcard can support domainless names.  The plan is to simply generate a cert which will match the domainless backend names.

First you need this PR patch of mine allowing arbitrary additions to the dns SAN names injected into the mantl certs.  It's only two files (and one is readme), so you might just want to paste the file into your working git repo.
https://github.com/CiscoCloud/mantl/pull/1307
Then wrap mantl's security setup with something like this
```
./my-security-setup  --dns-alt-cert-names-string 'DNS:k9b9-mantl-worker-001, DNS:k9b9-mantl-worker-002, DNS:k9b9-mantl-worker-003, DNS:*.node.example.com, DNS:*.example.com
```
You probably only need the first three terms 001-003 above.

Then run it. 
```
./my-security-setup.sh

```
Next, test that you generated the desired certs
```
openssl x509 -in ssl/certs/host.cert.pem -text | grep -A2 Alternative
```

and re-run ansible updating the certs
If you are pre-consolidation of all nginx certs to host.key and host.cert you will need to run mesos, marathon, traefik, consul roles.
Post that change, you can just run common role, just enough to hit this task
TASK: [common | deploy root ca] 

You can determine which you need by 
mantl> grep host.key .
and do the latter if you get any hits.

Now get wildcard_ssl.yml playbook from my second PR
https://github.com/CiscoCloud/mantl/pull/1445
It's a tasks list, so i wrap it in a customize.yml playbook for my company

My PR has an example of how to wrap that with customize.yml which should be templatized or customized to your needs.
```
ansible-playbook -i plugins/inventory/terraform.py playbooks/customize.yml -e @security.yml -e @your-vars.yml
```

open up ssh terms on edge01 and edge02 and
```
tail -f /var/log/traefik/traefik.log
```

I had to bounce all my containers for them to pick up the new certs.  Certs get loaded into memory at container start.
Now hit the frontends.  You should see no more X509 errors.   Check the logs via the mesos UI if there are other errors.

2016/05/19 13:56:53 [ERR] (view) "service(mongodb-prod-ihc [any])" health services: error fetching: Get https://consul.service.consul:8500/v1/health/service/mongodb-prod-ihc?stale=&wait=60000ms: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "security-setup")

**Comment by siddharthist** [comment]
@kbroughton We can't use Vault to generate the certificates, because the certificates need to be present for Vault to be initialzed :chicken: <-> :egg:

It seems like what you and @distributorofpain are discussing is a separate issue, can you please make a new one, rather than post on this?

**Comment by siddharthist** [comment]
Also, #1463 fixes the Traefik problem you're describing by issuing certificates that are valid for the bare hostnames as well.

**Comment by distributorofpain** [comment]
I might be missing something....  we are creating docker containers with software in them that is running a tomcat instance or java instance that uses a certificate.  When i spin them up in marathon, how are these changes going to allow that to work?  right now, we are putting the mantl general cert in the containers and rebuilding them.  Is that fix working outside the container?  Also, to apply, do i have to recreate the environment( justy verifying )?  I am still trying to figure out the internals of this setup :)

**Comment by kbroughton** [comment]
@siddharthist  You were right!  Your PR solved all my problems.  Traefik with ssl end to end is working.
The key was having the hostname and ip in the certs generated on the hosts.  Nicely done!

As for vault.  Our plan was to generate some bootstrap certs, and then use vault for everything else.  However, i'm pretty happy with what we have with this pr.

Ship it!

**Comment by kbroughton** [comment]
@distributorofpain i didn't get lucky with my update.  I rebuilt from scratch with this pr.

**Comment by distributorofpain** [comment]
Thanks @kbroughton !!  Rather not have to rebuild, but i suppose its just a thing...  Course, now i need to figure out how to do that with a PR...  i am such a github noob.

**Comment by kbroughton** [comment]
@distributorofpain That's not so hard:  from your mantl repo
mantl (master) > git checkout -b branch-to-store-your-work
                        > git add (any existing mantl files you modified)
                        > git commit -m "work in progress"
                        > git checkout feature/certificates-role
                        You are now ready to rock.
                         If you need any of the changes you made in your stashed branch
                         > git merge branch-to-store-your-work

**Comment by distributorofpain** [comment]
Thanks @kbroughton , So does this replace the solution you were using:  get security-setup certificates and install them in each docker image?  Trying to figure out if there is any change or update i need to do with regards to those.

**Comment by distributorofpain** [comment]
Is this now included in the current master?

**Comment by distributorofpain** [comment]
ok, still learning... not committed yet(question answered).  I was able to pull the repo to my mantl deployment server, then i was able to merge the pull request into the newly pulled repo.  I then deployed the merged repo and i see the certificate setup as noted.

My question now:  What do i need to include in the docker images so that traefik will trust them( so end to end ssl works)?

Note:  i am using docker containers, so i would assume they would need some certificate in them to operate with SSL.  Can that be any cert or does it need to be a specific cert?  Still confused as to how that would work...

So very close :smiley:

**Comment by distributorofpain** [comment]
well, i was able to get the application to pull in the certificate from the host as suggested, but now traefik doesnt like the certificate authority... argh! :frowning:

```
Jun  7 00:58:13 mantl-do-nyc2-edge-01 traefik: time="2016-06-07T00:58:13Z" level=error msg="Error forwarding to https://mantl-do-nyc2-worker-001:7254, err: x509: certificate signed by unknown authority"
```

Being that all the servers were built using the same setup and that the certs generate on each host, how can you get traefik to trust each host server as the authority?

**Comment by distributorofpain** [comment]
it looks like the CA cert is in the /etc/pki/ca-trust/source/anchors directory on the traefik server .  I also ran the /bin/update-ca-trust command again, but still getting that "certificate signed by unknown authority".  

I went to the host server and verified the /etc/pki/CA/ca.cert matched

**Comment by siddharthist** [comment]
@distributorofpain I'm not sure how you get Traefik to trust the generated CA. It looks like it has options for a CA server (for integrating with Let's Encrypt) and for a CA certificate for Docker TLS, but not one for general HTTP connections [1]. 

You might want to file an issue with Traefik itself, maybe something like "Set up list of trusted CA certificates".

Also: you can use `/etc/pki/CA/ca.cert` for the CA certificate, which is a bit shorter :smile:  

[1] https://docs.traefik.io/toml/

**Comment by distributorofpain** [comment]
oh perhaps thats the issue!  I was using /etc/pki/mantl/cert  it was declaring that host cert as having the invalid authority.

I did have the app setup to pull the /etc/pki/CA/ca.cert into the image and then append it to the /etc/pki/mantl/cert , but that wouldnt be right based on what you are saying....

I will update the script to pull /etc/pki/CA/ca.cert only and use it as the app certificate.

**Comment by distributorofpain** [comment]
just to clarify, is the host certificate supposed to be used as well?  IE: use the host cert and then append the CA to the bottom?

The host cert path i am using is: /etc/pki/mantl/cert

**Comment by siddharthist** [comment]
@distributorofpain I'm a little confused about what you mean. Here's a quick outline:

The CA has two certificates:
 1. a public cert (`/etc/pki/CA/ca.cert` and a few other places) that can be used to verify certificates signed by that CA.
 2. a private cert that is uses to sign other certificates

Additionally, each of our nodes has two certificates:
 1. A public certificate (`/etc/pki/mantl/cert`) that is used to encrypt data sent to that node and was signed by our CA.
 2. A private key (`/etc/pki/mantl/key`) that the node uses to prove its identity

Does that clarify things?

**Comment by ChrisAubuchon** [comment]
On an unrelated topic, is this PR still valid since short name resolution has been removed with https://github.com/asteris-llc/mantl-packaging/pull/98 and https://github.com/asteris-llc/mantl-packaging/pull/100?

**Comment by siddharthist** [comment]
Nope!

**Comment by siddharthist** [comment]
@distributorofpain Please open another issue or find me on Gitter if you'd like to discuss further!
