### ISSUE TITLE
move certificate generation into Terraform

### ISSUE THREAD

**Issue by siddharthist** [CiscoCloud/mantl#1517]
Apparently, [Terraform can generate TLS certificates](https://www.terraform.io/docs/providers/tls/index.html)! Right now, to make a cert with the right IP, we use the following pipeline:
```
terraform -> terraform.py -> Ansible -> generate-certificates -> openssl
```
whereas if we just used terraform directly, it would look like this:
```
terraform -> openssl
```
Let's cut out the middlemen and speed up our deployments!

The only question is how to include a resource in all of our terraform configurations. I suppose we can create a new module (called "common" or similar). 

- Ansible version (`ansible --version`): 
- Python version (`python --version`):
- Git commit hash or branch: 
- Cloud Environment: 
- Terraform version (`terraform version`):

**Comment by kbroughton** [comment]
terraform is very fast, but I have not found any way for it to play nice with pre-existing infrastructure.   We often have this need with on-site deployments or in 3rd party hosted aws scenarios.

I played with terraforming (https://github.com/dtan4/terraforming) but it is only half-baked, and it is very dangerous to run terraform against existing infra since it will happily delete all your goodies if there is a mismatch in the .tf and tfstate files.   Personally, i think that your creation playbook should be separate from your destruction playbook which is hard to support with terraform without switching between IAM privileges, but that's another matter.

I was able to make minor changes to mantl.yml to run it with static hosts.  Any thing that makes the general case faster and simpler is good, but please make sure it also supports the use-case of pre-existing infrastructure.

**Comment by siddharthist** [comment]
This really isn't feasible for supporting bare metal deployments.
