### ISSUE TITLE
SSO via Keycloak

### ISSUE THREAD

**Issue by xied75** [CiscoCloud/mantl#919]
Dear all,

Is there consideration for integrate a single sign on solution into mantl?

Best,

Dong

**Comment by stevendborrelli** [comment]
Dong, 

We haven't had any concrete discussions in this area yet. 

What are you thinking of using for SSO?

**Comment by xied75** [comment]
Well I was looking at keycloak (JBOSS) recently. They have many features that are useful for Microservices patterns: either end user authz, or chaining auth between different components, etc.

**Comment by stevendborrelli** [comment]
@xied75 that looks really useful. Would you be interested in working with us to make it an example application?

**Comment by xied75** [comment]
Deploying keycloak in container is not difficult, using it in user-end apps is up to the apps to understand it. If on the other hand you mean fully "integrate" this into mantl as a central piece, then that's a much bigger decision, but that wouldn't be a "example application" :)

**Comment by stevendborrelli** [comment]
It would be firmly in the camp of an application deployed via docker. 

Our vault support is not there yet, but we are hoping to enhance support soon so that you can mount secrets (like SSL) into a container. 

Also, we should not have example apps. Let's make it something you would want to use in production. 

@ryane can work with you to add it to our package repo.

**Comment by stevendborrelli** [comment]
I'm closing this. Please reopen if you want to discuss making this an example application.
